### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jnpetersen** [IRLToolkit/obs-websocket-http#10]
I'm on a Mac and when I try executing the downloaded `obs-websocket-http-v1-macOS` file (after chmod +x) I get the following:

```
INFO:root:HTTP server will start without authentication.
INFO:root:Connecting to obs-websocket...
ERROR:root:Identification with obs-websocket timed out. Could it be using 4.x?
```

I had recently installed the latest version of obs-websocket on my mac prior to finding this, but whenever I run it, I get this issue.  Any idea how I can fix/get around this?

**Comment by tt2468** [comment]
As the error suggests, it seems that your server could be using a 4.x version. Make sure you are using obs-websocket `5.0.0-beta1`.
