### ISSUE TITLE
Docker not pulling requirements.txt

### ISSUE THREAD

**Issue by airbornelamb** [IRLToolkit/obs-websocket-http#13]
Ran across a couple issues running in Docker:

- Docker-compose is not executing correctly because the Dockerfile is not referencing the requirements.txt file.
- Some minor changes needed to docker-compose.yml as obs-websocket is not v5 by default

I have fixed to make this work and will submit a PR. @tt2468 can you label the repo with hacktoberfest topic?

**Comment by tt2468** [comment]
Done, thanks!

**Comment by tt2468** [comment]
Fixed in 324ffef0a7b20938c9f4fc90afb019d967755938
