### ISSUE TITLE
Unable to connect from outside container

### ISSUE THREAD

**Issue by eaflores1** [IRLToolkit/obs-websocket-http#4]
Thank you so much for this obs-websocket-http solution. I really like it. However, I spent a bit of time figuring out how to call the API from windows using Docker. I was getting  "Error: socket hang up" from Postmand and node-red and getting "empty response" from localhost windows curl when calling http://{my ip}/call/GetSceneList.

I think the Docker instructions should mention to set docker-compose.yml to API_ADDRESS=0.0.0.0  instead of API_ADDRESS=127.0.0.1 otherwise the API will only be accessible within container and not from localhost.

**Comment by tt2468** [comment]
Fixed, thanks for letting me know.
