### ISSUE TITLE
question about config

### ISSUE THREAD

**Issue by arievanden** [IRLToolkit/obs-websocket-http#5]
Hello. I'm on CentOS7 and I found and installed python3.8. Hope that is ok. My question is about the config. I'm pointing the [obsws] config to the remote ip where OBS is hosted along with the default port 4444. Does the [http] config reference the "command" server that is sending curl commands to the remote OBS server? Thanks!

**Comment by tt2468** [comment]
The `[http]` section is what interface to bind to aka the local machine that python is running on.

**Comment by arievanden** [comment]
Ok, thanks!
