### ISSUE TITLE
Send an OBS websocket using a simple static http *only* page

### ISSUE THREAD

**Issue by Barabba11** [IRLToolkit/obs-websocket-http#7]
Hi mate!
Thank you for your precious script, sorry to create a bug for asking this question, I hope it may be useful to many other people, who just want to have a simple http pages (so compatible with all platforms without installing any app) with pictures of scenes to change, a simple press will produce the result. Thank you for your support!
In the OBS forum they suggested me this script (an example):

```
<div id="e0" class="cc08">
<a href="#" onclick="setCurrentScene('Scene2')">
<img src="logo.jpg" border="0" alt="Logo" title="Logo">
</a>
</div>

<script>
function setCurrentScene(scenename) {
var url = 'http://192.168.24.2:81/emit/SetCurrentScene';
var xhr = new XMLHttpRequest();
xhr.open('POST', url);

xhr.setRequestHeader("Content-Type", "application/json");

xhr.onreadystatechange = function () {
if (xhr.readyState === 4) {
console.log(xhr.status);
console.log(xhr.responseText);
}
};

var data = '{"scene-name":"'+scenename+'"}';

xhr.send(data);
}
</script>
```

I've tested it and unfortunately it doesn't work, I've debug it with a sniffer and I've found this:

The browser send the command but I think it misses the object cotaining scene:
E +q@À¨À¨¦FQ&´ô×P²çOPTIONS /emit/SetCurrentScene HTTP/1.1
Host: 192.168.24.2:81
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
Accept: */*
Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Origin: null
Connection: keep-alive

Your script replies this:
Eâ+v@À¨À¨Q¦F´ô×P²)HTTP/1.1 405 Method Not Allowed
Content-Type: text/plain; charset=utf-8
Allow: POST
Content-Length: 23
Date: Sat, 01 May 2021 09:47:09 GMT
Server: Python/3.8 aiohttp/3.7.4.post0

Wha tis wrong there?
Thanks

**Comment by Barabba11** [comment]
Hi author, I'm not an expert of HTTP but somebody told me the script is well written, the problem is that the browser somehow tries to reply to the first http server (which host the http page) and your server (on port 81) doesn't answer properly. May you make it compatible to answer? Than you a lot!

**Comment by Barabba11** [comment]
Hi, for many days I've asked all forums around how can I send a simple object inside an http page.. no luck.
May you kindly help me? Can you please introduce a way to change scenes from an http page? Thank you from heart

**Comment by tt2468** [comment]
Unfortunately I am not a web developer, so I can't help here.

**Comment by Barabba11** [comment]
thak you for kind help, may you please test this script? Who is expert told it works, but just the server-python script doesn't reply properly. Maybe you can change something in python server to let this script work? Thank you a lot!

**Comment by jbarrios** [comment]
Hello,
I had the same problem as you, my application is hosted on nginx using SSL and what I created as workarround was 2 proxypasses.

```
    location /obs/emit {
        proxy_pass http://192.168.24.2:81/emit;
    }
    location /obs/call {
        proxy_pass http://192.168.24.2:81/call;
    }
```

Instead of calling directly to http://192.168.24.2:81 I call the domain with https -> https://mydomain.com/obs/emit/XXXXXX

This is a solution that works to me

**Comment by Barabba11** [comment]
Thank you my friend for you really kind suggestion. Glad it works for you! Since I'm not an expert of HTTP can I ask you please to modify my html page to work as you said? Thank you a lot!

**Comment by Barabba11** [comment]
For who is interested, I've found the solution. Websockets plugin's team developed a js library that makes everthing easy, the browser will direct send data to websocket port:
https://obsproject.com/forum/threads/obs-websocket-remote-control-obs-studio-from-websockets.58018/post-536864
