### ISSUE TITLE
TypeError on run

### ISSUE THREAD

**Issue by jcrossbdn** [IRLToolkit/obs-websocket-http#9]
Just did a fresh install (and updated obs-websocket to 5 on the obs machine).  I am now receiving a TypeError:

```
root@streamfork:/opt/obs-websocket-http# python3.7 main.py
INFO:root:HTTP server will start with AuthKey set to `xxxxxxx`
INFO:root:Connecting to obs-websocket...
INFO:root:Connected to obs-websocket.
Traceback (most recent call last):
  File "main.py", line 136, in <module>
    web.run_app(app, host=httpAddress, port=httpPort, loop=loop)
TypeError: run_app() got an unexpected keyword argument 'loop'
```

Any ideas?

Hardware: Raspberry Pi 4 Model B Rev 1.4
OS: Raspbian GNU/Linux 10 (buster)

**Comment by tt2468** [comment]
Just pushed a change. Redownload and try again

**Comment by tt2468** [comment]
You can also download this binary which should work without needing python installed or the dependencies:
`wget https://github.com/IRLToolkit/obs-websocket-http/releases/download/v1/obs-websocket-http-v1-Ubuntu`

**Comment by jcrossbdn** [comment]
@tt2468 that update has solved it. Thank you!
